### ISSUE TITLE
Support toleration for `node-role.kubernetes.io/control-plane`

### ISSUE THREAD

**Issue by salv-orlando** [vmware/nsx-container-plugin-operator#191]
### Describe the bug

We are currently applying the toleration for deploying NCP on control plane nodes by leveraging the `node-role.kubernetes.io/master` label, which is however deprecated.

We should be supporting also `node-role.kubernetes.io/control-plane`

### Reproduction steps

```bash
N/A
```

### Expected behavior

In a K8S cluster where control plane nodes are labelled with node-role.kubernetes.io/control-plane the NCP operator should be able to apply  a toleration for this node label.

### Additional context

N/A

**Comment by timdengyun** [comment]
Hi Salvatore, Thanks for raising up this issue.  we are using  node-role.kubernetes.io/master label as a toleration for both
ncp, nsx-ncp-bootstrap and nsx-node-agent pods. So, I believe we should add node-role.kubernetes.io/control-plane to
for nsx-ncp-bootstrap and nsx-node-agent as well, is it correct? 

In addition, we need to add this change for ncp manifest template for non-operator env as well, is it?

**Comment by timdengyun** [comment]
The issue is resolved.
