### ISSUE TITLE
NCP Bootstrap init fails on Red Hat CoreOS

### ISSUE THREAD

**Issue by StevenBarre** [vmware/nsx-container-plugin-operator#196]
### Describe the bug

[Red Hat CoreOS](https://docs.openshift.com/container-platform/4.9/architecture/architecture-rhcos.html) is an immutable operating system used for the host OS of OpenShift 4 nodes. As such, most of its filesystems are mounted read-only.

Currently the NCP Bootstrap DeamonSet uses a host mount for `/var/lib/rpm` and then attempts to remove an RPM that is not installed in RHCOS.

If the [extensions](https://docs.openshift.com/container-platform/4.9/post_installation_configuration/machine-configuration-tasks.html#rhcos-add-extensions_post-install-machine-configuration-tasks) feature has been used to install additional packages in RHCOS, the bootstrap will fail when it tries to clean up the RPM database on the read-only filesystem.

### Reproduction steps

1. Add a MachineConfig to OpenShift to install the kernel-devel package in RHCOS

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 02-worker-kernel-devel
spec:
  extensions:
    - kernel-devel
```

2. After the nodes have rebooted, the bootstrap deamonset pods will be in a CrashLoop state with the following logs

```console
$ oc logs -c nsx-ncp-bootstrap nsx-ncp-bootstrap-vw8ss
2022-06-02T18:57:10Z mcs-klab2-master-03.dmz NSX 312121 - [nsx@6876 comp="nsx-container-node" subcomp="NSX-NCP-
BOOTSTRAP" level="INFO"] .usr.local.bin.init_k8s_node Detected host OS: Red Hat Enterprise Linux CoreOS
2022-06-02T18:57:11Z mcs-klab2-master-03.dmz NSX 312121 - [nsx@6876 comp="nsx-container-node" subcomp="NSX-NCP-
BOOTSTRAP" level="INFO"] .usr.local.bin.init_k8s_node NSX-CNI build not detected on the host. Creating a new bu
ild.
rm: cannot remove '/var/lib/rpm/__db.001': Read-only file system
rm: cannot remove '/var/lib/rpm/__db.002': Read-only file system
rm: cannot remove '/var/lib/rpm/__db.003': Read-only file system
```

3. Editing the bootstrap deamonset to remove the host-path mount of `/var/lib/rpm` allows the bootstrap pods to start. But this is unstable as the operator may overwrite the deamonset.

### Expected behavior

Bootstrap pods start, even if the `extensions` feature has been used to add packages to the RHCOS image.

### Additional context

https://github.com/vmware/nsx-container-plugin-operator/blob/9ef762c63e7d1e99f52ce3a685dc6e6e6983ea0f/manifest/openshift4/coreos/ncp-openshift4.yaml#L766-L768

**Comment by ggverma** [comment]
This bug was also opened in the internal VMware bug repo. There is no straightforward workaround at the moment. It is going to be fixed in the next release. So closing this issue.

**Comment by StevenBarre** [comment]
@ggverma what is the next release version number and approx when will it be released?
