### ISSUE TITLE
Error: exec: init_k8s_node not found in PATH in v4.1.1/v4.1.2 image in nsx-ncp-bootstrap pod

### ISSUE THREAD

**Issue by daliborfilus** [vmware/nsx-container-plugin-operator#242]
### Describe the bug

The released image https://hub.docker.com/r/vmware/nsx-container-plugin-operator:v4.1.1 (and :v4.1.2) throws an error during `nsx-ncp-bootstrap-xxxx` pod.
The error says the command `init_k8s_node` is not present in PATH during exec and the bootstrap container never starts.

Searching through this repository, I found it's referenced from this file:
vmware/nsx-container-plugin-operator/blob/release_4.1.1/manifest/openshift4/coreos/ncp-openshift4.yaml#L715
(and it's the same for all the other platforms, too).

In operator.yaml, we have set the `image:` to `docker.io/vmware/nsx-container-plugin-operator:v4.1.1`, and `NCP_IMAGE` to the same value, `docker.io/vmware/nsx-container-plugin-operator:v4.1.1`. Is that correct?
(We have mirror on the production cluster, I'm using the original image tags here for clarity.)

The code in this repository defaults to `nsx-ncp:latest` for `NcpImage`, but there's no such image. Is this the old name of this operator image?
(Interted search refers to `nsx-ncp-ubi:latest`, which doesn't exist anywhere either.)

Some other, non-official images from the dockerhub have `init_k8s_node` binary in them, for example `okdtj/nsx-ncp-ubi:4.1.1.1.22355203` has it. The official ones (v4.0.0, v4.1.1, v4.1.2) don't.

Official documentation on vmware.com doesn't say what exact value should be put there, if it's the same image, or something completely different.
See here: https://docs.vmware.com/en/VMware-NSX-Container-Plugin/4.1/ncp-openshift/GUID-303605D3-6447-45FE-8FE1-3CAF0F7FC578.html
It left us wondering if we are using the correct image for `NCP_IMAGE` above, since the documentation says only this:

> For example, for NCP 3.1.1, the operator image is vmware/nsx-container-plugin-operator:v3.1.1.
But it doesn't say anything about `NCP_IMAGE`. I don't know if its intended to be the same image.

(Btw image v4.1.2 is currently broken, so we had to rollback to v4.1.1. But even v4.1.2 doesn't have init_k8s_node in it.)

### Reproduction steps

1. Install NCP operator plugin - edit operator.yaml and all the other required files.
2. Install OpenShift cluster.
3. Inspect the logs of nsx-ncp-bootstrap, watch it crash repeatedly on init_k8s_node. (Init:ContainerCreateFailed)

### Expected behavior

It should not crash.

### Additional context

OpenShift 4 installation on VMware VMs with NSX.

**Comment by timdengyun** [comment]
and NCP_IMAGE to the same value, docker.io/vmware/nsx-container-plugin-operator:v4.1.1. Is that correct?
This is not correct. docker.io/vmware/nsx-container-plugin-operator is NCP Operator Image not NCP itself. NCP is not open source product. You have to get its image from Customer connect with VMware. https://customerconnect.vmware.com/downloads/details?downloadGroup=NSX-T-PKS-411&productId=1324

After you download it and you can set NCP image to the one you imported.

**Comment by daliborfilus** [comment]
@timdengyun Thank you. Then the documentation (linked above) could be a candidate for a big improvement here. There isn't a single instruction that you should download the NCP image from vmware.com and that it's in fact different image from the operator. There are some instructions to download the openshift4.tar.gz from github.com/vmware..., but there isn't anything about the NCP image. This is the text referring to the downloads (emphasis mine):

> For the **operator** image, specify the NCP version that will need to be installed. For example, for NCP 3.1.1, the operator image is vmware/nsx-container-plugin-operator:v3.1.1.

> Note that pulling directly **dockerhub** is not recommended in a production environment because of its rate limiting policy. Once pulled from **dockerhub**, the image can be pushed to a local registry, **possibly the same where NCP images are available**.

> Alternatively, you can use the **operator** image file included in the NCP **download** **file** from **download.vmware.com** and import it into a local registry. This **image** is the **same** as the one published on VMware's **dockerhub**.

You can see the instructions where to get the operator image are there, but not the NCP image. The documentation assumes I already know this, but I don't, since I just got the instructions to install openshift on top of NSX and that's where I'm at, at that point in the process.

I can't find it in this repo's README either. It also assumes I already know what "NCP image" is.

Is it written somewhere else? Thank you for any directions.

**Comment by timdengyun** [comment]
@daliborfilus 
Thanks for your feedback. Much appreciation. We don't add more info on NCP itself in this NCP Operator product. 
You can find more info on NCP from NCP release note
https://docs.vmware.com/en/VMware-NSX-Container-Plugin/4.1/ncp-openshift/GUID-122645B5-A846-4BBA-BAF7-DA5B69E1B717.html

We assume already know NCP product prior to use NCP Operator, since NCP Operator is closely integrated with NCP.
We can get more detailed info from Release note of NCP:
https://docs.vmware.com/en/VMware-NSX-Container-Plugin/4.1.1/rn/vmware-nsx-container-plugin-411-release-notes/index.html
to help users understand what's NCP and how we get NCP Release build. Of course, it also cover Openshfit4 env installation guide with NCP Operator.
