### ISSUE TITLE
Support for cVDS connected node VMs

### ISSUE THREAD

**Issue by yasensim** [vmware/nsx-container-plugin-operator#39]
The operator successfully applies tags when the Logical Segments are realized on NVDS. However, with NSX3 and vSphere7 people have the option to use VDS(cVDS) instead of nVDS. Currently, the operator fails to apply the tags in this case and we need to apply them manually. cVDS will be the way going forward so the operator have to apply tags automatically when cVDS is used.

**Comment by heypnus** [comment]
Hi Yasen, I did a preliminary investigation about this issue and I think the latest [enhancement](https://github.com/vmware/nsx-container-plugin-operator/commit/2323f8fe1af7e8935a58a04559116b1779aad6a9) for node controller can resolve it. Could you help confirm if your operator build contains the commit which was merged last Friday?

**Comment by aidrees** [comment]
Hi Qian, i think your enhancement should solve it. The issue that Yasen reported is in an environment with VSAN and the ports names includes UID,

1190165f-5f3c-0728-d75d-0050568da9a3/control-plane-0.vmx@a2b95903-d170-4c0c-9fec-c5d5b3d7ab7e
2390165f-1ddd-b033-f13e-0050568da9a3/control-plane-1.vmx@a2b95903-d170-4c0c-9fec-c5d5b3d7ab7e
1690165f-9bdc-89f3-7cd3-0050568da9a3/control-plane-2.vmx@a2b95903-d170-4c0c-9fec-c5d5b3d7ab7e
1590165f-c553-c1c6-eb07-0050568da9a3/compute-0.vmx@a2b95903-d170-4c0c-9fec-c5d5b3d7ab7e
1090165f-8efa-6122-bec1-0050568da9a3/compute-1.vmx@a2b95903-d170-4c0c-9fec-c5d5b3d7ab7e

i will test the changes and let you know.

**Comment by aidrees** [comment]
I rebuild the nsx-ncp-operator image with Qian enhancement which solved the issue.
The test was successful with cVDS and VSAN on vSphere 7.
Thanks!
