### ISSUE TITLE
How to deploy on K8s

### ISSUE THREAD

**Issue by TYsewyn** [vmware/nsx-container-plugin-operator#47]
Hi! 👋
Recently I have been working with NSX-T at one of our customers and I stumbled upon this operator.
We are using our TKGi solution and I was wondering which steps we could take to deploy this operator on a regular, vendor agnostic Kubernetes cluster.
I believe that it could make this operator better and more widely available across many different companies and organisations.

**Comment by heypnus** [comment]
The support was introduced in 3.1.1, you can use the latest version to try it.
