### ISSUE TITLE
Add node selector and tolerations as option in the configmap

### ISSUE THREAD

**Issue by yasensim** [vmware/nsx-container-plugin-operator#54]
Currently it is not possible to dictate where NCP will be deployed as the deployment spec is applied by the operator. Customers want to be able to run NCP on master, infra, or compute nodes. we need to provide this option either in the operator configmap or as an env var.

@dantingl  and @salv-orlando  can we plan it?

**Comment by yasensim** [comment]
Also the daemon sets need to have configurable tolerations as many customers are using taints.

**Comment by timdengyun** [comment]
Issue fixed.

**Comment by timdengyun** [comment]
Hi gammohamed,
AS I know, there is no root password for ncp operator pod, you can access pod by using kubectl exec -it -n nsx-system-operator <operartor-pod-name> -- /bin/bash
but the file in the pod is not editable. 
If you want to change node selector and tolerations, you need to edit ncp-install CRD as in https://github.com/timdengyun/nsx-container-plugin-operator/commit/e6d7fe01e72c32703c662e9094102254c1b33674
