### ISSUE TITLE
nsx_api_password characters restrictions

### ISSUE THREAD

**Issue by LDSanches** [vmware/nsx-container-plugin-operator#69]
Hello,

During the deployment special characters such as "|" or "#" are not acceptable in the variable nsx_api_password insite of configmap.yaml.
When the operator configures configmap in the nsx-system, these special characters are not recognized.

**Comment by salv-orlando** [comment]
Hi @timdengyun  do you think we can target this issue to the next release?

**Comment by timdengyun** [comment]
> Hi @timdengyun do you think we can target this issue to the next release?

Hi @salv-orlando,  it looks like this is not a complicated fix, and we can try to fix this one 3.2 release. but given inventory enhancement  task, I'm not sure we have sufficient bandwidth to complete this fix in the next release. anyway, I will try my best.
