### ISSUE TITLE
Is ncp-openshift4.yaml needed?

### ISSUE THREAD

**Issue by aidrees** [vmware/nsx-container-plugin-operator#94]
just a small comment regarding the documentation. You mentioned "Put operator yaml files from deploy/openshift/ and manifests/openshift/coreos to MY_CLUSTER/manifests, edit configmap.yaml about operator configurations, add the operator image and NCP image in operator.yaml."

for me the bootstrap fail when i copy the ncp-openshift4.yaml file from /openshift/coreos, but all works good without it by only copying the deploy folder.

**Comment by heypnus** [comment]
Fixed doc by #98 , thanks for pointing it out.
